// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// worldAnalysis
List worldAnalysis(NumericVector& wave, double frameshift, int fs);
RcppExport SEXP WorldR_worldAnalysis(SEXP waveSEXP, SEXP frameshiftSEXP, SEXP fsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector& >::type wave(waveSEXP);
    Rcpp::traits::input_parameter< double >::type frameshift(frameshiftSEXP);
    Rcpp::traits::input_parameter< int >::type fs(fsSEXP);
    __result = Rcpp::wrap(worldAnalysis(wave, frameshift, fs));
    return __result;
END_RCPP
}
