# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

worldAnalysis_ <- function(wave, frameshift, fs, f0floor, allowed_range) {
    .Call('WorldR_worldAnalysis_', PACKAGE = 'WorldR', wave, frameshift, fs, f0floor, allowed_range)
}

worldAnalysis_f0 <- function(wave, Rf0, frameshift, fs, f0floor, allowed_range) {
    .Call('WorldR_worldAnalysis_f0', PACKAGE = 'WorldR', wave, Rf0, frameshift, fs, f0floor, allowed_range)
}

worldF0Estimation <- function(wave, frameshift, fs, f0floor, allowed_range) {
    .Call('WorldR_worldF0Estimation', PACKAGE = 'WorldR', wave, frameshift, fs, f0floor, allowed_range)
}

worldSynthesis_ <- function(world) {
    .Call('WorldR_worldSynthesis_', PACKAGE = 'WorldR', world)
}

